### ISSUE TITLE
Doctor Appointment System

### ISSUE THREAD

**Issue by afterallvishal** [GFGSC-RTU/GFG-SDE-Sheet-Solution-Kit#214]
This is a doctor appointment system code using C++,
@gfg-rtu kindly assign me this issue under Hacktoberfest 2022.

**Comment by afterallvishal** [comment]
@gfg-rtu kindly assign me this.

**Comment by DiyaVj** [comment]
Hey @afterallvishal  !
You can make PR directly. In this repo, it doesn't need to be specifically assigned. Thank You
